### ISSUE TITLE
[M3: R]

### ISSUE THREAD

**Issue by slumnitz** [UBC-MDS/DSCI-532-Group108-R#17]
Hello everyone,

you made good progress in creating functionality for the R app and merging each others PRs. What I would like to see for the next milestone is:
* that you use GitHub issues for communication or documentation of your communication if day to day communication is done via another service
* that you try and improve your commit messages. Instead of `add changes README` you could write `update R-viz in README`
* you could start using [DOC] = add and change documentation, [ENH] = add functionality or interactivity , [BUG]  = solve bug, to your messages to make them shorter. (your choice, many big open source collaborations use this)
* work on aesthetics and layout of your app

These are minor comments, well done overall!

**Comment by dkruszew** [comment]
Thank you.
Aesthetics tweeked. Further comments provided in updated reflection.md file
